# CD to Azure
name: CD

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: https://index.docker.io/v1/
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build . -t ${{ secrets.REGISTRY_USERNAME }}/colorthis_worker
        docker push ${{ secrets.REGISTRY_USERNAME }}/colorthis_worker
      
    - name: Pushing to Azure
      run: |
        az webapp config container set --resource-group Color-This --name colorthis --multicontainer-config-type compose --multicontainer-config-file docker-compose.yaml
 