# CD to Azure
name: CD

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: index.docker.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build . -t asedhain/colorthis_worker:${{ github.sha }}
        docker push asedhain/colorthis_worker:${{ github.sha }}
      
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'colorthis-worker'
        images: 'asedhain/colorthis_worker:${{ github.sha }}'
